# build with: docker build -f Dockerfile.relion-cuda --build-arg RELION_REF=ver5.0 --build-arg CUDA_VERSION=12.8.0 -t jidaniel/relion:5.0-cuda12.8 .
#         or: docker build -f Dockerfile.relion-cuda --build-arg RELION_REF=ver5.0 --build-arg CUDA_VERSION=12.4.1 -t jidaniel/relion:5.0-cuda12.4 .
#         or: docker build -f Dockerfile.relion-cuda --build-arg RELION_REF=ver5.0 --build-arg CUDA_VERSION=11.8.0 -t jidaniel/relion:5.0-cuda11.8 .
# run interactively with: docker run --gpus all -it --rm jidaniel/relion:5.0-cuda12.8 /bin/bash


ARG CUDA_VERSION=12.8.0
FROM nvidia/cuda:${CUDA_VERSION}-devel-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive
ARG RELION_REF=ver5.0

ARG CTFFIND_VER=4.1.14
ENV CTFFIND_HOME=/opt/ctffind-${CTFFIND_VER}


# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake git pkg-config \
    openmpi-bin libopenmpi-dev \
    libfftw3-dev libtiff-dev libpng-dev \
    ghostscript pbzip2 xz-utils zstd \
    ca-certificates \
    libfltk1.3-dev libx11-dev libxft-dev libxext-dev libxinerama-dev libxrender-dev \
    wget curl vim nano \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install CTFFind
WORKDIR /opt
RUN set -eux; \
  curl -fL "https://grigoriefflab.umassmed.edu/system/tdf?path=ctffind-${CTFFIND_VER}-linux64.tar.gz&file=1" -o /tmp/ctffind.tgz; \
  mkdir -p "$CTFFIND_HOME"; \
  tar -xzf /tmp/ctffind.tgz -C "$CTFFIND_HOME"; rm -f /tmp/ctffind.tgz; \
  install -m 0755 "$CTFFIND_HOME"/bin/* /usr/local/bin/

RUN which ctffind

# Install Miniconda
WORKDIR /opt
RUN curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh && \
    bash miniconda.sh -b -p /opt/conda && \
    rm miniconda.sh
ENV PATH=/opt/conda/bin:$PATH

# Clone RELION
WORKDIR /opt
RUN git clone https://github.com/3dem/relion.git --branch ${RELION_REF} --single-branch --depth 1
WORKDIR relion
RUN git fetch --all --tags && git checkout ${RELION_REF}

# Create Conda environment
RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
RUN conda env create -f /opt/relion/environment.yml && conda clean -afy

# Build RELION
RUN mkdir -p build
WORKDIR build
RUN cmake .. -DCMAKE_BUILD_TYPE=Release -DFETCH_WEIGHTS=OFF
RUN make -j"$(nproc)"
RUN make install

ENV PATH="/usr/local/bin:${PATH}"

RUN useradd -ms /bin/bash relion && chown -R relion:relion /opt
USER relion

WORKDIR /work
