FROM jidaniel/relion:5.0-cuda12.2.0

ARG PORTAL_PARTICLE_EXTRACTION_LOCATION=portal-particle-extraction
ARG PYRELION_LOCATION=relion-sub-tomogram-pipelines

# TODO: install octopi as well

COPY ${PORTAL_PARTICLE_EXTRACTION_LOCATION} /opt/portal-particle-extraction
COPY ${PYRELION_LOCATION} /opt/relion-sub-tomogram-pipelines

RUN conda create -n cdp-relion-sta python=3.11 -y
SHELL ["conda", "run", "-n", "cdp-relion-sta", "/bin/bash", "-c"]

RUN pip install uv
RUN pip install /opt/relion-sub-tomogram-pipelines
RUN pip install /opt/portal-particle-extraction
RUN pip install octopi
RUN conda clean -afy
RUN portal-particle-extraction --help
RUN pyrelion --help
RUN octopi --help