ARG DEBIAN_FRONTEND=noninteractive
ARG RELION_RELEASE=5.0
ARG CUDA_VERSION=12.8.0

FROM jidaniel/relion:${RELION_RELEASE}-cuda${CUDA_VERSION} AS base

ARG PORTAL_PARTICLE_EXTRACTION_LOCATION=portal-particle-extraction
ARG PYRELION_LOCATION=relion-sub-tomogram-pipelines

COPY ${PORTAL_PARTICLE_EXTRACTION_LOCATION} /opt/portal-particle-extraction
COPY ${PYRELION_LOCATION} /opt/relion-sub-tomogram-pipelines

SHELL ["/bin/bash", "-l", "-c"]
RUN micromamba create -n cdp-relion-sta python=3.11 -c conda-forge -y
SHELL ["micromamba", "run", "-n", "cdp-relion-sta", "/bin/bash", "-l", "-c"]

RUN pip install uv
RUN uv pip install /opt/relion-sub-tomogram-pipelines
RUN uv pip install /opt/portal-particle-extraction
RUN uv pip install octopi
WORKDIR /
USER root
RUN ["/bin/sh", "-c", "rm -rf /opt/relion-sub-tomogram-pipelines"]
RUN ["/bin/sh", "-c", "rm -rf /opt/portal-particle-extraction"]
USER relion
RUN pip cache purge
RUN micromamba clean -afy
RUN portal-particle-extraction --help
RUN pyrelion --help
RUN octopi --help